using NpgsqlTypes;

namespace QuestionsHub.Blazor.Domain;

/// <summary>
/// Represents a single question in the game.
/// </summary>
public class Question
{
    public int Id { get; set; }

    /// <summary>Physical order of the question within the tour (0-based).</summary>
    public int OrderIndex { get; set; }

    /// <summary>Question number for display (e.g., "1", "2", "F" for hexadecimal, "0" for warm-up).</summary>
    public required string Number { get; set; }

    /// <summary>Instructions for the host/organizer (Вказівка ведучому).</summary>
    public string? HostInstructions { get; set; }

    /// <summary>The main question text.</summary>
    public required string Text { get; set; }

    /// <summary>Text of handout material for the question.</summary>
    public string? HandoutText { get; set; }

    /// <summary>URL to handout image/attachment.</summary>
    public string? HandoutUrl { get; set; }

    /// <summary>The correct answer.</summary>
    public required string Answer { get; set; }

    /// <summary>Alternative accepted answers (залік).</summary>
    public string? AcceptedAnswers { get; set; }

    /// <summary>Answers that are explicitly not accepted.</summary>
    public string? RejectedAnswers { get; set; }

    /// <summary>Commentary explaining the answer.</summary>
    public string? Comment { get; set; }

    /// <summary>URL to commentary attachment (image for answer).</summary>
    public string? CommentAttachmentUrl { get; set; }

    /// <summary>Source references for the question facts.</summary>
    public string? Source { get; set; }

    /// <summary>Question authors.</summary>
    public List<Author> Authors { get; set; } = [];

    // Navigation properties
    public int TourId { get; set; }
    public Tour Tour { get; set; } = null!;

    /// <summary>Optional block ID. When tour has blocks, questions belong to blocks.</summary>
    public int? BlockId { get; set; }
    public Block? Block { get; set; }

    // Search columns (generated by database, read-only)

    /// <summary>Generated: Normalized search text (lowercase, no accents, ґ→г).</summary>
    public string? SearchTextNorm { get; private set; }

    /// <summary>Generated: FTS tsvector for full-text search.</summary>
    public NpgsqlTsVector? SearchVector { get; private set; }
}
