using System.ComponentModel.DataAnnotations.Schema;
using NpgsqlTypes;

namespace QuestionsHub.Blazor.Domain;

/// <summary>
/// Defines how question numbers are assigned within a package.
/// </summary>
public enum QuestionNumberingMode
{
    /// <summary>
    /// Questions are numbered sequentially across all main tours (1, 2, 3, ...).
    /// Warmup tour questions are numbered separately (1..k).
    /// </summary>
    Global,

    /// <summary>
    /// Questions are numbered sequentially within each tour (1, 2, ... per tour).
    /// </summary>
    PerTour,

    /// <summary>
    /// Question numbers are not auto-assigned. Users can edit them manually.
    /// Used for special cases like hexadecimal numbering (e.g., "IT-cup").
    /// </summary>
    Manual
}

/// <summary>
/// Represents a single question in the game.
/// </summary>
public class Question
{
    public int Id { get; set; }

    /// <summary>Physical order of the question within the tour (0-based).</summary>
    public int OrderIndex { get; set; }

    /// <summary>Question number for display (e.g., "1", "2", "F" for hexadecimal, "0" for warm-up).</summary>
    public required string Number { get; set; }

    /// <summary>Instructions for the host/organizer (Вказівка ведучому).</summary>
    public string? HostInstructions { get; set; }

    /// <summary>The main question text.</summary>
    public required string Text { get; set; }

    /// <summary>Text of handout material for the question.</summary>
    public string? HandoutText { get; set; }

    /// <summary>URL to handout image/attachment.</summary>
    public string? HandoutUrl { get; set; }

    /// <summary>The correct answer.</summary>
    public required string Answer { get; set; }

    /// <summary>Alternative accepted answers (залік).</summary>
    public string? AcceptedAnswers { get; set; }

    /// <summary>Answers that are explicitly not accepted.</summary>
    public string? RejectedAnswers { get; set; }

    /// <summary>Commentary explaining the answer.</summary>
    public string? Comment { get; set; }

    /// <summary>URL to commentary attachment (image for answer).</summary>
    public string? CommentAttachmentUrl { get; set; }

    /// <summary>Source references for the question facts.</summary>
    public string? Source { get; set; }

    /// <summary>Question authors.</summary>
    public List<Author> Authors { get; set; } = [];

    // Navigation properties
    public int TourId { get; set; }
    public Tour Tour { get; set; } = null!;

    /// <summary>Optional block ID. When tour has blocks, questions belong to blocks.</summary>
    public int? BlockId { get; set; }
    public Block? Block { get; set; }

    // Search columns (generated by database, read-only)

    /// <summary>Generated: Normalized search text (lowercase, no accents, ґ→г).</summary>
    public string? SearchTextNorm { get; private set; }

    /// <summary>Generated: FTS tsvector for full-text search.</summary>
    public NpgsqlTsVector? SearchVector { get; private set; }
}

/// <summary>
/// Defines the type of tour within a package.
/// </summary>
public enum TourType
{
    /// <summary>Regular (main) tour with sequentially numbered questions.</summary>
    Regular = 0,

    /// <summary>Warmup tour (Розминка). At most one per package. Always first.</summary>
    Warmup = 1,

    /// <summary>Shootout tour (Перестрілка). At most one per package. Always last.</summary>
    Shootout = 2
}

/// <summary>
/// Represents a tour (round) within a package.
/// </summary>
public class Tour
{
    public int Id { get; set; }

    /// <summary>Physical order of the tour within the package (0-based). Source of truth for ordering.</summary>
    public int OrderIndex { get; set; }

    /// <summary>Tour type: Regular, Warmup, or Shootout.</summary>
    public TourType Type { get; set; } = TourType.Regular;

    /// <summary>Whether this is a warmup tour.</summary>
    [NotMapped]
    public bool IsWarmup => Type == TourType.Warmup;

    /// <summary>Whether this is a shootout (Перестрілка) tour.</summary>
    [NotMapped]
    public bool IsShootout => Type == TourType.Shootout;

    /// <summary>Whether this is a special (non-regular) tour.</summary>
    [NotMapped]
    public bool IsSpecial => Type != TourType.Regular;

    /// <summary>Tour number for display (e.g., "1", "2"). For main tours, assigned sequentially. For warmup, may be "0" or empty.</summary>
    public required string Number { get; set; }

    /// <summary>Tour editors/authors.</summary>
    public List<Author> Editors { get; set; } = [];

    /// <summary>Preamble - information from editors about the tour, usually contains list of testers (Преамбула).</summary>
    public string? Preamble { get; set; }

    /// <summary>Commentary for the entire tour.</summary>
    public string? Comment { get; set; }

    // Navigation properties
    public int PackageId { get; set; }
    public Package Package { get; set; } = null!;
    public List<Question> Questions { get; set; } = [];
    public List<Block> Blocks { get; set; } = [];

    /// <summary>Whether this tour has blocks.</summary>
    [NotMapped]
    public bool HasBlocks => Blocks.Count > 0;

    /// <summary>
    /// Gets all editors for the tour. If tour has blocks, returns all unique editors from all blocks.
    /// Otherwise, returns the tour's own editors.
    /// </summary>
    [NotMapped]
    public IEnumerable<Author> AllEditors => HasBlocks
        ? Blocks.SelectMany(b => b.Editors).DistinctBy(a => a.Id)
        : Editors;
}

/// <summary>
/// Represents a question package (tournament package).
/// </summary>
public class Package
{
    public int Id { get; set; }

    /// <summary>Package title.</summary>
    public required string Title { get; set; }

    /// <summary>Start date when the package was played (or single date for one-day events).</summary>
    public DateOnly? PlayedFrom { get; set; }

    /// <summary>End date when the package was played (null for single-day events).</summary>
    public DateOnly? PlayedTo { get; set; }

    /// <summary>URL where the package was originally obtained (e.g., from .qhub import).</summary>
    public string? SourceUrl { get; set; }

    /// <summary>Package description or notes.</summary>
    public string? Description { get; set; }

    /// <summary>Preamble - information from editors about the package, usually contains list of testers (Преамбула).</summary>
    public string? Preamble { get; set; }

    /// <summary>Total number of questions in the package.</summary>
    public int TotalQuestions { get; set; }

    /// <summary>Package visibility status.</summary>
    public PackageStatus Status { get; set; } = PackageStatus.Draft;

    /// <summary>Access control level - determines who can view the package.</summary>
    public PackageAccessLevel AccessLevel { get; set; } = PackageAccessLevel.All;

    /// <summary>How question numbers are assigned in this package.</summary>
    public QuestionNumberingMode NumberingMode { get; set; } = QuestionNumberingMode.Global;

    /// <summary>When true, all tours share the same editors defined at package level.</summary>
    public bool SharedEditors { get; set; }

    /// <summary>Date and time when the package was published (UTC).</summary>
    public DateTime? PublicationDate { get; set; }

    /// <summary>The ID of the user who owns this package.</summary>
    public string? OwnerId { get; set; }

    /// <summary>The user who owns this package.</summary>
    public ApplicationUser? Owner { get; set; }

    // Navigation properties
    public List<Tour> Tours { get; set; } = [];

    /// <summary>Editors assigned directly to the package (used when SharedEditors is true).</summary>
    public List<Author> PackageEditors { get; set; } = [];

    /// <summary>Tags associated with this package.</summary>
    public List<Tag> Tags { get; set; } = [];

    /// <summary>
    /// Gets the effective editors for the package.
    /// When SharedEditors is true, returns PackageEditors.
    /// Otherwise, returns all unique editors from all tours (computed, not stored in DB).
    /// </summary>
    [NotMapped]
    public IEnumerable<Author> Editors => SharedEditors
        ? PackageEditors
        : Tours.SelectMany(t => t.AllEditors).DistinctBy(a => a.Id);
}
